# ==============================================================
# = Sdi Configurazione Web Service - Versione Base
# ==============================================================
server:
  port: 8000

spring:
  application:
    name: sdiconfigurazioneservice
  profiles:
    include: swagger
 
# ==============================================================
# = DBMS PostgreSQL Parameters
# ==============================================================
  datasource:
    url: ${DEFAULT_DB_URL}
    username: ${DEFAULT_DB_USER}
    password: ${DEFAULT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public #simeal
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  sql:
    init:
      mode: always
      platform: postgres 

# ==============================================================
# = Swagger & OpenAPI Parameters
# ==============================================================
springdoc:
  api-docs.yaml:
    path: /v3/api-docs.yaml
  swagger-ui:
    path: /swagger

# ==============================================================
# = JHipster Parameters
# ==============================================================
jhipster:
  clientApp:
    name: 'sdiconfigurazioneserviceApp'

# ==============================================================
# = Actuator Parameters
# ==============================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers #"*" # mostra tutti
  endpoint:
    loggers:
      enabled: true

# ==============================================================
# = Actuator Parameters
# ==============================================================
info:
  informazioni-generali:
    azienda: ICCS
  informazioni-app:
    nome-app: Sdi Configurazione Service
    descrizione: Microservizio di Configurazione per Simeal

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
