# ==============================================================
# = Sdi Configurazione Web Service - Versione Base
# ==============================================================
server:
  port: 8000

#java:
#  runtime:
#    version: 11
#
#maven:
#  version: 3.6.2

spring:
  application:
    name: sdiconfigurazioneservice
  profiles:
    include: swagger



  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-214-125-106.eu-west-1.compute.amazonaws.com:5432/d2o9b7v5iv4u2p
    username: mqwpnfavktyywu
    password: dd3cd0a53903fbe1a54730c0815d7e0cfd900d329a7b9b0483a2b863a46a8029
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  # ==============================================================
  # = DBMS PostgreSQL Parameters
  # ==============================================================
  #  datasource:
  #    url: ${DEFAULT_DB_URL}
  #    username: ${DEFAULT_DB_USER}
  #    password: ${DEFAULT_DB_PASSWORD}
  #  jdbc:postgresql://YourPostgresHerokuHostNameHere:5432/YourPostgresHerokuDatabase
  # https://stackoverflow.com/questions/33633243/connecting-to-heroku-postgres-from-spring-boot


#datasource:
#  url: jdbc:postgresql://localhost:5432/sdi_configurazione
#  username: postgres
#  password: root

#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        default_schema: public #simeal
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        jdbc:
#          lob:
#            non_contextual_creation: true
#    show-sql: true
#  sql:
#    init:
#      mode: always
#      platform: postgres

# ==============================================================
# = Swagger & OpenAPI Parameters
# ==============================================================
springdoc:
  api-docs.yaml:
    path: /v3/api-docs.yaml
  swagger-ui:
    path: /swagger

# ==============================================================
# = JHipster Parameters
# ==============================================================
jhipster:
  clientApp:
    name: 'sdiconfigurazioneserviceApp'

# ==============================================================
# = Actuator Parameters
# ==============================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers #"*" # mostra tutti
  endpoint:
    loggers:
      enabled: true

# ==============================================================
# = Actuator Parameters
# ==============================================================
info:
  informazioni-generali:
    azienda: ICCS
  informazioni-app:
    nome-app: Sdi Configurazione Service
    descrizione: Microservizio di Configurazione per Simeal

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
